# -*- coding: utf-8 -*-
"""Authprocpubper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_e8AeJSzu1GC19OgdCw4JfJ0RP7f8Pls
"""

!pip install xlsxwriter
import pandas as pd
from google.colab import files

uploaded = files.upload()
file_path = next(iter(uploaded))

excel_data = pd.ExcelFile(file_path)
output_path = '/content/finalxl.xlsx'
writer = pd.ExcelWriter(output_path, engine='xlsxwriter')

for sheet_name in excel_data.sheet_names:
    df = excel_data.parse(sheet_name)
    df = df[df['Cites'] != 0]
    df = df.sort_values(by='Cites', ascending=False)
    df['Serial Number'] = range(1, len(df) + 1)
    df.to_excel(writer, sheet_name=sheet_name, index=False)

writer.close()

files.download(output_path)