# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.
"""
!pip install pandas numpy matplotlib python-docx scipy xlsxwriter xlrd openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from docx import Document
from docx.shared import Inches
from google.colab import files
from scipy.optimize import minimize
import zipfile
import os


uploaded = files.upload()

if not os.path.exists('plots'):
    os.makedirs('plots')
if not os.path.exists('excels'):
    os.makedirs('excels')


summary_data = []
model_params_data = []
fitted_values_data = []

def calculate_h_index(y_data):
    sorted_cites = np.sort(y_data)[::-1]
    h_index = np.max(np.where(sorted_cites >= np.arange(1, len(sorted_cites) + 1))[0]) + 1
    return h_index

def calculate_abc(M, N, h):
    a = (M * h**2) / (M * N - (M + N) * h)
    b = (M * N * (M - h) * (N - h)) * (h / (M * N - (M + N) * h))**2
    c = (N * h**2) / (M * N - (M + N) * h)
    return a, b, c

def calculate_abc_h_formula(M, N, h):
    a = -(-M*N + M*h**2 - M*h + M + N*h - h**2)/(-M*N + M*h + N*h - 2*h + 1)
    c = -(-M*N + M*h + N*h**2 - N*h + N - h**2)/(-M*N + M*h + N*h - 2*h + 1)
    b = (-M + h)*(M - 1)*(-N + h)*(N - 1)*(h - 1)**2/(-M*N + M*h + N*h - 2*h + 1)**2
    return a, b, c

def calculate_abc_10h(M, N, h):
    a = -M * h * (h - 1) / (-M * N + M * h + N * h - h)
    b = M * h * (-M + h) * (-N + h) * (N - 1) * (h - 1) / (-M * N + M * h + N * h - h)**2
    c = -(-M * N + M * h + N * h**2 - h**2) / (-M * N + M * h + N * h - h)
    return a, b, c

def calculate_rmse(y_true, y_pred):
    return np.sqrt(np.mean((y_true - y_pred) ** 2))

def optimize_abc(x_data, y_data):
    def objective(params):
        a, b, c = params
        fitted_values = (b / (x_data + c)) - a
        return calculate_rmse(y_data, fitted_values)

    initial_guess = [0.1, 100, 72]
    result = minimize(objective, initial_guess, method='Nelder-Mead')
    return result.x

def optimize_power_law(x_data, y_data):
    def objective(params):
        C, lam = params
        fitted_values = C / (x_data ** lam)
        return calculate_rmse(y_data, fitted_values)

    initial_guess = [np.max(y_data), 1]
    result = minimize(objective, initial_guess, method='Nelder-Mead')
    return result.x

def zip_dir(dir_path, ziph):

    for root, dirs, files in os.walk(dir_path):
        for file in files:
            ziph.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), os.path.join(dir_path, '..')))


for file_name in uploaded.keys():
    xls = pd.ExcelFile(file_name)

    doc = Document()
    doc.add_heading('Plots for Each Sheet', 0)

    for sheet_name in xls.sheet_names:
        df = pd.read_excel(xls, sheet_name=sheet_name)
        x_data = df['Serial Number'].values
        y_data = df['Cites'].values

        M = np.max(y_data)
        N = len(y_data)
        h = calculate_h_index(y_data)

        a, b, c = calculate_abc(M, N, h)
        fitted_values = (b / (x_data + c)) - a
        rmse_original = calculate_rmse(y_data, fitted_values)

        a_opt, b_opt, c_opt = optimize_abc(x_data, y_data)
        fitted_values_opt = (b_opt / (x_data + c_opt)) - a_opt
        rmse_eqn2 = calculate_rmse(y_data, fitted_values_opt)

        C_opt, lambda_opt = optimize_power_law(x_data, y_data)
        fitted_values_power_law = C_opt / (x_data ** lambda_opt)
        rmse_power_law = calculate_rmse(y_data, fitted_values_power_law)

        a_h, b_h, c_h = calculate_abc_h_formula(M, N, h)
        fitted_values_h = (b_h / (x_data + c_h)) - a_h
        rmse_h = calculate_rmse(y_data, fitted_values_h)

        a_10h, b_10h, c_10h = calculate_abc_10h(M, N, h)
        fitted_values_10h = (b_10h / (x_data + c_10h)) - a_10h
        rmse_10h = calculate_rmse(y_data, fitted_values_10h)

        summary_data.append({
            'File': file_name,
            'Sheet': sheet_name,
            'M': M,
            'N': N,
            'h': h
        })

        model_params_data.extend([
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CE00h',
                'Parameters': f"{a:.2f},{b:.2f},{c:.2f}, RMSE: {rmse_original:.2f}"
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CEMinrmse',
                'Parameters': f"{a_opt:.2f},{b_opt:.2f},{c_opt:.2f}, RMSE: {rmse_eqn2:.2f}"
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'PLminRMSE',
                'Parameters': f"{C_opt:.2f},{lambda_opt:.2f}, RMSE: {rmse_power_law:.2f}"
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CE11h',
                'Parameters': f"{a_h:.2f},{b_h:.2f},{c_h:.2f}, RMSE: {rmse_h:.2f}"
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CE10h',
                'Parameters': f"{a_10h:.2f},{b_10h:.2f},{c_10h:.2f}, RMSE: {rmse_10h:.2f}"
            }
        ])

        fitted_values_data.extend([
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CE00h',
                'Fitted Values': fitted_values.tolist()  # Convert to list to avoid array format
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CEMinrmse',
                'Fitted Values': fitted_values_opt.tolist()  # Convert to list to avoid array format
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'PLminRMSE',
                'Fitted Values': fitted_values_power_law.tolist()  # Convert to list to avoid array format
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CE11h',
                'Fitted Values': fitted_values_h.tolist()  # Convert to list to avoid array format
            },
            {
                'File': file_name,
                'Sheet': sheet_name,
                'Model': 'CE10h',
                'Fitted Values': fitted_values_10h.tolist()  # Convert to list to avoid array format
            }
        ])

      
        plt.figure(figsize=(10, 6))
        plt.scatter(x_data, y_data, label='Data Points')
        plt.plot(x_data, fitted_values, label='CE00h')
        plt.plot(x_data, fitted_values_opt, label='CEMinrmse')
        plt.plot(x_data, fitted_values_power_law, label='PLminRMSE')
        plt.plot(x_data, fitted_values_h, label='CE11h')
        plt.plot(x_data, fitted_values_10h, label='CE10h')
        plt.title(f'Fitted Models for {sheet_name}')
        plt.xlabel('Serial Number')
        plt.ylabel('Cites')
        plt.legend()
        plt.grid(True)
        plt.tight_layout()

       
        plt.savefig(f'plots/{file_name}_{sheet_name}.png')
        plt.close()

        doc.add_heading(f'Plot for {sheet_name}', level=1)
        doc.add_picture(f'plots/{file_name}_{sheet_name}.png', width=Inches(6))

    
    doc.save(f'excels/{file_name}_plots.docx')


summary_df = pd.DataFrame(summary_data)
model_params_df = pd.DataFrame(model_params_data)
fitted_values_df = pd.DataFrame(fitted_values_data)

summary_df.to_excel('summary.xlsx', index=False)
model_params_df.to_excel('model_params.xlsx', index=False)
fitted_values_df.to_excel('fitted_values.xlsx', index=False)


with zipfile.ZipFile('output.zip', 'w') as zipf:
    zipf.write('summary.xlsx')
    zipf.write('model_params.xlsx')
    zipf.write('fitted_values.xlsx')
    zip_dir('plots', zipf)
    zip_dir('excels', zipf)


files.download('output.zip')
