# -*- coding: utf-8 -*-
"""ECCSUMcalculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FN6s0i-bbl-XxWvmC4opMSFjydaiNq_G
"""

!pip install xlsxwriter pandas openpyxl numpy

import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

results = pd.DataFrame(columns=['File_Sheet', 'Cites_Sum'])

for file_name in uploaded.keys():
    xls = pd.ExcelFile(file_name)
    for sheet_name in xls.sheet_names:
        df = pd.read_excel(xls, sheet_name=sheet_name)
        if 'Cites' in df.columns:
            cites_sum = df['Cites'].replace(np.nan, 0).sum()
            results = pd.concat([results, pd.DataFrame({'File_Sheet': [f"{file_name}_{sheet_name}"], 'Cites_Sum': [cites_sum]})], ignore_index=True)
        else:
            results = pd.concat([results, pd.DataFrame({'File_Sheet': [f"{file_name}_{sheet_name}"], 'Cites_Sum': ['No Cites column']})], ignore_index=True)

results.to_excel('cites_sums.xlsx', index=False)

files.download('cites_sums.xlsx')