# -*- coding: utf-8 -*-
"""eq calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166TJV8OI6ZWmoumv37MQ-3NlVRfY6UkY
"""

import sympy as sp

a, b, c, M, N, h = sp.symbols('a b c M N h')

eq1 = sp.Eq(b - a - a*c, M + M*c)
eq2 = sp.Eq(b - a*N - a*c, N + c)
eq3 = sp.Eq(b - a*h - a*c + h**2 + c*h, 0)

solutions = sp.solve((eq1, eq2, eq3), (a, b, c))

solutions