# -*- coding: utf-8 -*-
"""hindexhisto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEM06kzkidSxFg3ZDpIbrbbTEHyAvph_
"""

!pip install pandas numpy matplotlib python-docx openpyxl scipy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

def calculate_h_index(y_data):
    sorted_cites = np.sort(y_data)[::-1]
    h_index = np.max(np.where(sorted_cites >= np.arange(1, len(sorted_cites) + 1))[0]) + 1
    return h_index

def optimal_bins(data):
    q25, q75 = np.percentile(data, [25, 75])
    bin_width = 2 * (q75 - q25) * len(data) ** (-1/3)
    bins = int((data.max() - data.min()) / bin_width)
    return bins

uploaded = files.upload()

file_name = list(uploaded.keys())[0]
xls = pd.ExcelFile(file_name)

h_indices = []
for sheet_name in xls.sheet_names:
    df = pd.read_excel(xls, sheet_name=sheet_name)
    if 'ECC' in df.columns:
        ecc_values = df['ECC'].dropna().values
        h_index = calculate_h_index(ecc_values)
        h_indices.append(h_index)

bins = optimal_bins(np.array(h_indices))

plt.hist(h_indices, bins=bins, edgecolor='black')

plt.xlabel('h-index bins')
plt.ylabel('Number of authors')
plt.title('Histogram of h-index values across all sheets')

plt.show()