# -*- coding: utf-8 -*-
"""Mhisto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEM06kzkidSxFg3ZDpIbrbbTEHyAvph_
"""

!pip install pandas numpy matplotlib python-docx openpyxl scipy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

def calculate_M(y_data):
    return np.max(y_data)

def optimal_bins(data):
    q25, q75 = np.percentile(data, [25, 75])
    bin_width = 2 * (q75 - q25) * len(data) ** (-1/3)
    bins = int((data.max() - data.min()) / bin_width)
    return bins

uploaded = files.upload()

file_name = list(uploaded.keys())[0]
xls = pd.ExcelFile(file_name)

M_values = []
for sheet_name in xls.sheet_names:
    df = pd.read_excel(xls, sheet_name=sheet_name)
    if 'ECC' in df.columns:
        ecc_values = df['ECC'].dropna().values
        M = calculate_M(ecc_values)
        M_values.append(M)

bins = optimal_bins(np.array(M_values))

plt.hist(M_values, bins=bins, edgecolor='black')

plt.xlabel('M bins')
plt.ylabel('Number of authors')
plt.title('Histogram of M values across all sheets')

plt.show()