# -*- coding: utf-8 -*-
"""multiplexlsxhist0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183QIKs6o8pyuuVzYa86c2kKl1CJsUIUW
"""

!pip install pandas numpy matplotlib python-docx openpyxl scipy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

def calculate_h_index(y_data):
    sorted_cites = np.sort(y_data)[::-1]
    h_index = np.max(np.where(sorted_cites >= np.arange(1, len(sorted_cites) + 1))[0]) + 1
    return h_index

def calculate_M(y_data):
    return np.max(y_data)

def calculate_N(y_data):
    return len(y_data)

uploaded = files.upload()

h_indices = []
M_values = []
N_values = []
summary_data = []

for file_name in uploaded.keys():
    xls = pd.ExcelFile(file_name)
    for sheet_name in xls.sheet_names:
        df = pd.read_excel(xls, sheet_name=sheet_name)
        if 'ECC' in df.columns:
            ecc_values = df['ECC'].dropna().values
            h_index = calculate_h_index(ecc_values)
            M_value = calculate_M(ecc_values)
            N_value = calculate_N(ecc_values)
            h_indices.append(h_index)
            M_values.append(M_value)
            N_values.append(N_value)
            summary_data.append({
                'File Name': file_name,
                'Sheet Name': sheet_name,
                'h-index': h_index,
                'M': M_value,
                'N': N_value
            })

summary_df = pd.DataFrame(summary_data)

output_file = 'summary.xlsx'
summary_df.to_excel(output_file, index=False)

bins = 18

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.hist(h_indices, bins=bins, edgecolor='black')
plt.xlabel('h-index bins')
plt.ylabel('Number of authors')
plt.title('Histogram of h-index values across all sheets')

plt.subplot(1, 3, 2)
plt.hist(M_values, bins=bins, edgecolor='black')
plt.xlabel('M bins')
plt.ylabel('Number of authors')
plt.title('Histogram of M values across all sheets')

plt.subplot(1, 3, 3)
plt.hist(N_values, bins=bins, edgecolor='black')
plt.xlabel('N bins')
plt.ylabel('Number of authors')
plt.title('Histogram of N values across all sheets')

plt.tight_layout()
plt.show()

files.download(output_file)

!zip -r plots.zip plots