# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FN6s0i-bbl-XxWvmC4opMSFjydaiNq_G
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
import io
import numpy as np

uploaded = files.upload()

for filename in uploaded.keys():
    excel_file = pd.ExcelFile(io.BytesIO(uploaded[filename]))

def plot_theta_scatter_with_regression(excel_file):
    for sheet_name in excel_file.sheet_names:
        df = excel_file.parse(sheet_name)
        if "Theta (empirical)" in df.columns and "Theta (equation)" in df.columns:
            x = df["Theta (empirical)"]
            y = df["Theta (equation)"]

            plt.figure(figsize=(8, 6))
            plt.scatter(x, y, label='Data points')

            coefficients = np.polyfit(x, y, 1)
            polynomial = np.poly1d(coefficients)
            regression_line = polynomial(x)

            plt.plot(x, regression_line, color='red', label='Regression line')
            plt.xlabel("Theta (empirical)")
            plt.ylabel("Theta (equation)")
            plt.title(f'Scatter Plot with Regression Line for {sheet_name}')
            plt.legend()
            plt.grid(True)
            plt.show()

plot_theta_scatter_with_regression(excel_file)