# -*- coding: utf-8 -*-
"""thetacalculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FN6s0i-bbl-XxWvmC4opMSFjydaiNq_G
"""

!pip install pandas openpyxl

import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    df = pd.read_excel(filename)

if not all(col in df.columns for col in ['M', 'N', 'h']):
    raise ValueError("The input file must contain 'M', 'N', and 'h' columns.")

euler_number = 2.71828
df['Theta (equation)'] = df.apply(lambda row: row['h']**2 * np.log((row['M'] * row['N']) / (euler_number * row['h']**2)), axis=1)

output_filename = "output_with_theta.xlsx"
df.to_excel(output_filename, index=False)

files.download(output_filename)